workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
          - pattern: '*'
            include: true
            source: true
    integrations:
      app_store_connect: App Manager Ilke
    environment:
      groups:
        - firebase_credentials
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: ilkeyucel.codemagic.task
      vars:
        APP_ID: 6479329113
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          echo "Installing pods"
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build ipa and automatic versioning
        script: |
          new_build_number=$(expr $BUILD_NUMBER + 100)
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$new_build_number \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        ios:
          app_id: $FIREBASE_APP_ID
          groups: 
            - "iosTesters"